export const COUNTRIES_ENG = [
  'Abkhazia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Albania',
  'Algeria',
  'US Virgin Islands (USA)',
  'Anguilla (WB)',
  'Angola',
  'Andorra',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba (Netherlands)',
  'Afghanistan',
  'Bahamas',
  'Bangladesh',
  'Barbados',
  'Bahrain',
  'Belize',
  'Belarus',
  'Belgium',
  'Benin',
  'Bermuda (Wb)',
  'Bulgaria',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands (Wb)',
  'Brunei',
  'Burkina Faso',
  'Burundi',
  'Butane',
  'Vanuatu',
  'Great Britain',
  'Hungary',
  'Venezuela',
  'East Timor',
  'Vietnam',
  'Gabon',
  'Haiti',
  'Guyana',
  'Gambia',
  'Ghana',
  'Guadeloupe (FR)',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Germany',
  'Gibraltar (UK)',
  'Honduras',
  'Grenada',
  'Greenland (Dn)',
  'Greece',
  'Georgia',
  'Guam (USA)',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Egypt',
  'Zambia',
  'West Sahara',
  'Zimbabwe',
  'Israel',
  'India',
  'Indonesia',
  'Jordan',
  'Iraq',
  'Iran',
  'Ireland',
  'Iceland',
  'Spain',
  'Italy',
  'Yemen',
  'Cape Verde',
  'Kazakhstan',
  'Cayman Islands (Wb)',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Caribbean Netherlands',
  'Qatar',
  'Kenya',
  'Cyprus',
  'Kyrgyzstan',
  'Kiribati',
  'China',
  'Cocos (Keeling) Islands (Av)',
  'Colombia',
  'Comoros',
  'Democratic Republic of the Congo',
  'Republic of the Congo',
  'Kosovo',
  'Costa Rica',
  'Ivory Coast',
  'Cuba',
  'Kuwait',
  'Curacao',
  'Laos',
  'Latvia',
  'Lesotho',
  'Liberia',
  'Lebanon',
  'Libya',
  'Lithuania',
  'Liechtenstein',
  'Luxembourg',
  'Mauritius',
  'Mauritania',
  'Madagascar',
  'Mayotte (Fr)',
  'Malawi',
  'Malaysia',
  'Mali',
  'Maldives',
  'Malta',
  'Morocco',
  'Martinique (Fr)',
  'Marshall Islands',
  'Mexico',
  'micronesia',
  'Mozambique',
  'Moldova',
  'Mongolia',
  'Montserrat (Wb)',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Niger',
  'Nigeria',
  'Netherlands Antilles (Sun)',
  'Nicaragua',
  'Niue (New Zealand[2])',
  'New Caledonia (Fr)',
  'New Zealand',
  'Norway',
  'United Arab Emirates',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Pitcairn (WB)',
  'Poland',
  'Portugal',
  'Puerto Rico (USA)',
  'Reunion (FR)',
  'Russia',
  'Romania',
  'Salvador',
  'Samoa',
  'American Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Swaziland',
  'Saint Helena (Wb)',
  'Northern Mariana Islands (USA)',
  'North Korea',
  'North Macedonia',
  'Seychelles',
  'Saint Barthélemy (FR)',
  'Saint Martin (Fr, Sun)',
  'Saint Pierre and Miquelon (Fr)',
  'Saint Vincent and the Grenadines',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Senegal',
  'Serbia',
  'Singapore',
  'Sint Maarten',
  'Syria',
  'Slovakia',
  'Slovenia',
  'Solomon islands',
  'Somalia',
  'Sudan',
  'Suriname',
  'USA',
  'Sierra Leone',
  'Tajikistan',
  'Taiwan',
  'Thailand',
  'Tanzania',
  'Turks and Caicos Islands (Wb)',
  'Togo',
  'Tokelau (New Zealand[3])',
  'Tonga',
  'Trinidad and Tobago',
  'Tuvalu',
  'Tunisia',
  'Turkmenistan',
  'Turkey',
  'Uganda',
  'Uzbekistan',
  'Ukraine',
  'Uruguay',
  'Faroe Islands (Dn)',
  'Fiji',
  'Philippines',
  'Finland',
  'Falkland Islands (Wb[4])',
  'France',
  'French Guiana (Fr)',
  'French Polynesia (Fr)',
  'Croatia',
  'Central African Republic',
  'Chad',
  'Montenegro',
  'Czech',
  'Chile',
  'Switzerland',
  'Sweden]',
  'Sri Lanka',
  'Ecuador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'South Korea',
  'Republic of South Africa',
  'South Sudan',
  'Jamaica',
  'Japan',
];
